---
leo_manager_0_port_cui:     10010
leo_manager_0_port_json:    10020

leo_manager_0_rpc_port:     13075

leofs_num_of_replica:   2
leofs_write_quorum:     1
leofs_read_quorum:      1
leofs_delete_quorum:    1
