---

## For Fetching Package 
- hosts: localhost
  gather_facts: False
  roles:
      - role: controller

- hosts: leo_manager_0
  roles:
      - role: leo_manager_0

- hosts: leo_manager_1
  roles:
      - role: leo_manager_1

## Wait for LeoManagers Startup
- hosts: localhost
  gather_facts: False
  tasks:
    - name: Wait for LeoMansgers
      pause: seconds=5
      tags: 
          - run

- hosts: leo_storage
  roles:
      - role: leo_storage

- hosts: leo_gateway
  roles:
      - role: leo_gateway

## Wait for LeoStorage Startup
- hosts: localhost
  gather_facts: False
  tasks:
    - name: Wait for LeoStorages
      pause: seconds=30
      tags: 
          - run

## Start LeoFS
- hosts: localhost
  gather_facts: False
  tasks:
      - name: Start LeoFS
        command: ./leofs-adm start
        tags: 
            - run
