---

- hosts: localhost
  gather_facts: False
  roles:
      - role: controller

- hosts: leo_manager_0
  roles:
      - role: leo_manager_0

- hosts: leo_manager_1
  roles:
      - role: leo_manager_1

- hosts: localhost
  gather_facts: False
  tasks:
      - name: Sleep 5 Seconds
        command: sleep 5
        tags: run

- hosts: leo_storage
  roles:
      - role: leo_storage

- hosts: leo_gateway
  roles:
      - role: leo_gateway

- hosts: localhost
  gather_facts: False
  tasks:
      - name: Sleep 30 Seconds
        command: sleep 30
        tags: run

- hosts: localhost
  gather_facts: False
  tasks:
      - name: Start LeoFS
        command: ./leofs-adm start
        tags: run
