---

## Stop LeoFS
- hosts: leo_manager_0
  name: Start LeoManager (Primary)
  roles:
      - { role: leo_manager_0, control_leofs: "stop" }

- hosts: leo_manager_1
  name: Start LeoManager (Secondary)
  roles:
      - { role: leo_manager_1, control_leofs: "stop" }

- hosts: leo_storage
  name: Start LeoStorages
  roles:
      - { role: leo_storage, control_leofs: "stop" }

- hosts: leo_gateway
  name: Start LeoGateway
  roles:
      - { role: leo_gateway, control_leofs: "stop" }
