---
- hosts: leo_storage
  roles:
    - { role: common, do_install: true }

- hosts: leo_storage
  roles:
    - { role: leo_storage, do_config: true }

- hosts: leo_storage
  name: Start LeoStorages
  roles:
    - { role: leo_storage, control_leofs: "start" }
