---
- name: Create the LeoGateway Configuration File
  template: src=leo_gateway.conf.j2 dest={{ leofs_module_conf_path }}/leo_gateway.conf
  when: (do_purge is undefined or do_purge == false) and get_log is undefined
  tags:
      - config

- name: Include Control Tasks
  include: control.yml
  when: control_leofs is defined

- name: Include Purge Instructions
  include: purge.yml
  when: do_purge is defined and do_purge
