---
- name: Include Leofs Package Information
  include_vars: leofs_releases/{{ leofs_version }}.yml
  tags: 
      - install

- name: Pick Package based on OS
  include_vars: "{{ item }}"
  with_first_found:
      - "package_{{ ansible_distribution }}_{{ansible_distribution_version}}.yml"
      - "package_{{ ansible_distribution }}_{{ansible_lsb.major_release}}.yml"
      - "package_{{ ansible_distribution }}.yml"
      - "package_{{ ansible_os_family }}.yml"
  tags: 
      - install

- name: Check Cached LeoFS Package (at Controller)
  local_action: stat path=/tmp/{{ leofs_package }}
  register: cached_package
  tags: 
      - install

- name: Copy LeoFS Package
  copy: src=/tmp/{{ leofs_package }} dest=/tmp/
  when: cached_package.stat.exists == True
  tags: 
      - install

- name: Get LeoFS Package
  get_url:
      url: "{{ leofs_package_url }}"
      dest: "/tmp/{{ leofs_package }}"
  when: cached_package.stat.exists == False
  tags: 
      - install

- name: Install LeoFS Package
  become: True
  apt: deb=/tmp/{{ leofs_package }}
  tags: 
      - install

- name: Prepare Directories
  become: True
  file: 
      path: "{{ item }}"
      state: directory
  with_items:
      - "{{ leofs_work_dir }}"
      - "{{ leofs_mnesia_dir }}"
      - "{{ leofs_queue_dir }}"
      - "{{ leofs_stack_dir }}"
      - "{{ leofs_log_dir }}"
  tags:
      - config

- name: Force Stop
  become: True
  command: pkill beam.smp 
  ignore_errors: True
  tags:
      - killbeam

- name: Uninstall LeoFS Package
  become: True
  apt: name=leofs state=absent
  tags:
      - uninstall
      - purge

- name: Purge LeoFS
  become: True
  file: path={{ leofs_install_path }} state=absent
  tags:
      - purge
