---
- name: Include Package Installation Tasks
  include: install_package.yml
  when: do_install is defined and do_install and source == "package"

- name: Include Build Installation Tasks
  include: install_build.yml
  when: do_install is defined and do_install and source == "build"

- name: Point to Build Package Path
  set_fact:
    leofs_install_path: "{{ build_install_path }}/package"
  when: source == "build"

- name: Include Common Perparation
  include: config.yml
  when: do_config is defined and do_config

- name: Include Common Force Kill (beam.smp)
  include: forcekill.yml
  when: do_forcekill is defined and do_forcekill

- name: Include Common Purge Instructions
  include: purge.yml
  when: do_purge is defined and do_purge
