---

- name: Run LeoManager (Secondary)
  command: bin/leo_manager start
  when: control_leofs is defined and control_leofs == "start"
  args:
    chdir: "{{ leofs_module_path }}"
  tags:
      - run

- name: Stop LeoManager (Secondary)
  command: bin/leo_manager stop
  when: control_leofs is defined and control_leofs == "stop"
  args:
    chdir: "{{ leofs_module_path }}"
  tags:
      - stop

