---

- name: Create the LeoManager (Secondary) Configuration File
  template: src=leo_manager_1.conf.j2 dest={{ leofs_module_conf_path }}/leo_manager.conf
  when: (do_purge is undefined or do_purge == false) and get_log is undefined
  tags:
    - config

- name: Include Control Tasks
  include: control.yml
  when: control_leofs is defined
